feat: #108 Adding logic for demo logo
Informasjonsforvaltning/fdk-admin-gui pull request #109
Opened 2021-10-18 11:24 UTC by frederik-ronnevig

Legger på parametere for å håndtere demologo (som finnes i felles toolkit)

Closes #108

2021-10-18 12:58 UTC, matsjs commented on src/components/header/index.tsx
> +      useDemoLogo={env.ENV === 'development'}
Bruk gjerne enum'en her 👍 
```suggestion
      useDemoLogo={env.ENV === Environment.DEVELOPMENT
```

2021-10-19 07:02 UTC, frederik-ronnevig commented on src/components/header/index.tsx
> +      useDemoLogo={env.ENV === 'development'}
He he, ja selvfølgelig, tåpelig feil :blush:

2021-10-19 08:01 UTC, frederik-ronnevig commented
@oyvindis sa seg villig til fikse audit-feilene i en egen branch

2021-11-02 10:57 UTC, matsjs approved these changes

2021-11-02 11:00 UTC, oyvindis commented on src/components/header/index.tsx
> +      useDemoLogo={env.ENV === Environment.DEVELOPMENT}
Jeg tror ikke det vil fungere å gjøre slik her. ENV settes i webpack, enten til development eller production avhengig av hvilket bygg som kjøres. Helm-fil deployer production-image til demo så her vil ENV være "production". Så kun i staging vil ENV === Environment.DEVELOPMENT.

I f.eks. fdk-portal finnes det en egen env-variabel "useDemoLogo" som settes spesifikt i gcp i alle tre miljøer, tror man må inn med det samme her.

2021-11-02 11:01 UTC, oyvindis requested changes
Se kommentar.

2021-11-02 11:02 UTC, frederik-ronnevig commented on src/components/header/index.tsx
> +      useDemoLogo={env.ENV === Environment.DEVELOPMENT}
Ok @oyvindis , takk for at du sa i fra, skulle akkurat til å merge! :innocent: Men da er det tilbake til tegnebordet igjen

2021-11-02 11:15 UTC, oyvindis commented on src/components/header/index.tsx
> +      useDemoLogo={env.ENV === Environment.DEVELOPMENT}
@frederik-ronnevig Du kan få Hans Olav til å legge inn env-variabel i GCP for demo USE_DEMO_LOGO: 'True', så endrer du bare til å sjekke mot den variabelen.

Når man oppretter ny variabel, husk å oppdatere config.template.js, /src/env.ts og /src/types/env.d.ts i tillegg.

2021-11-04 09:26 UTC, oyvindis approved these changes

2021-11-04 12:12 UTC, merged