Feat/jr/auth header
Informasjonsforvaltning/fdk-admin-gui pull request #124
Opened 2022-03-15 10:43 UTC by jeffreiffers

2022-03-15 11:24 UTC, NilsOveTen approved these changes

2022-03-17 08:25 UTC, NilsOveTen requested changes
i frontend oppfører den seg nå som om authHeader er obligatorisk

Kanskje legge til en checkbox elns for å aktivere/deaktivere den?

2022-03-18 10:57 UTC, jeffreiffers commented
> i frontend oppfører den seg nå som om authHeader er obligatorisk
> 
> Kanskje legge til en checkbox elns for å aktivere/deaktivere den?

Fikset!

2022-03-22 08:43 UTC, NilsOveTen approved these changes

2022-03-22 08:44 UTC, NilsOveTen approved these changes

2022-03-25 08:56 UTC, oyvindis approved these changes
I tillegg squash "auth should not be required" med den opprinnelige.

2022-03-25 09:39 UTC, merged