feat: new design
Informasjonsforvaltning/fdk-admin-gui pull request #82
Opened 2021-02-03 21:49 UTC by jeffreiffers

2021-02-04 06:56 UTC, oyvindis commented on src/components/data-source-item/styled.ts
> +  background-color: #d5edf2;
Kan du bruke farger fra theme her?

2021-02-04 07:04 UTC, oyvindis commented on src/entrypoints/main/router/styled.ts
> +      font-size: calc(24px + (48 - 24) * ((100vw - 320px) / (1020 - 320)));
Skjønner ikke hvorfor denne må beregnes. Kan den ikke bare settes til en statisk 'rem'? På margin kan du heller bruke 'em' så blir margin responsiv i forhold til font-size.

2021-02-04 07:06 UTC, oyvindis commented on src/components/root/styled.ts
> +      font-size: calc(24px + (48 - 24) * ((100vw - 320px) / (1020 - 320)));
Må den beregnes slik?

2021-02-04 08:46 UTC, azaxarov requested changes

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-source-item-editor/index.tsx
> +              label='Organization number'
Unødvendig diff

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-source-item-editor/validation-schema.ts
> +    .matches(/^\d{9}$/, 'Organization number must be a 9-digit value'),
Unødvendig diff

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-source-item/styled.ts
> +  background-color: #d5edf2;
kan bruke `background` property i stedet

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-sources-page/index.tsx
> +    organizations.find(org => org.organizationId === id) ?? {
```suggestion
    organizations.find(({ organizationId }) => organizationId === id) ?? {
```

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-sources-page/index.tsx
> +  const getOrganization = (id: string): Organization =>
Denne trenger vel ikke noe fallback. Hvis ikke det finnes en organisasjon, kan det håndteres uten fallback

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-sources-page/index.tsx
> +  fetchOrganizations();
Se kommentar om useEffect over

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-sources-page/redux/reducer.ts
> +    case FETCH_ORGANIZATIONS_SUCCEEDED:
Kan være greit å dekke requested og failed states

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-sources-page/redux/saga.ts
> +          organizationId: ids.join(',')
```suggestion
          organizationId: ids.join()
```

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-sources-page/styled.ts
> +
```suggestion
import { theme, Colour } from '@fellesdatakatalog/theme';
```

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-sources-page/styled.ts
> +import AddIconBase from '../../images/add-circle-icon.svg';
```suggestion

import AddIconBase from '../../images/add-circle-icon.svg';
```

2021-02-04 08:46 UTC, azaxarov commented on src/components/root/styled.ts
> +      font-size: calc(24px + (48 - 24) * ((100vw - 320px) / (1020 - 320)));
Det er en fin måte å gjøre text størrelse "responsiv"

2021-02-04 08:46 UTC, azaxarov commented on src/components/side-menu/index.tsx
> +const SideMenu: FC<Props> = ({ title, authService, location }) => {
react-router-dom har en komponent som heter NavLink tror jeg, som går an å bruke her

2021-02-04 08:46 UTC, azaxarov commented on src/components/root/styled.ts
> +  padding: 0 20px 20px 20px;
```suggestion
  padding: 20px;
```

2021-02-04 08:46 UTC, azaxarov commented on src/components/side-menu/styled.ts
> +  margin-left: 20px;
```suggestion
```

2021-02-04 08:46 UTC, azaxarov commented on src/entrypoints/main/router/styled.ts
> +      font-size: calc(24px + (48 - 24) * ((100vw - 320px) / (1020 - 320)));
https://css-tricks.com/snippets/css/fluid-typography/

2021-02-04 08:46 UTC, azaxarov commented on src/entrypoints/main/router/styled.ts
> +  margin: 80px 20px;
Bruk gjerne theme.spacing

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-sources-page/index.tsx
> +    if (!organizations.length) {
kan ta bort if-setning

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-sources-page/index.tsx
> +
```suggestion
import Button, { Variant } from '@fellesdatakatalog/button';
```

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-source-item/index.tsx
> +import { Variant } from '@fellesdatakatalog/button';
```suggestion
import { Variant } from '@fellesdatakatalog/button';
```

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-source-item/index.tsx
> +import { DataSource, Organization } from '../../types';
```suggestion
import type { DataSource, Organization } from '../../types';
```

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-source-item/index.tsx
> +          <SC.DataSourceTypeDatasets>
Jeg ville vurdert å heller lage en type styled komponent som tar imot DataSource type property

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-source-item/styled.ts
> +  display: block;
Er ikke den block by default?

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-source-item/styled.ts
> +  flex-direction: row;
row er default
```suggestion
```

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-source-item/styled.ts
> +  & > button {
:nth-of-type(n + 2) er fortsatt nødvendig

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-source-item/styled.ts
> +  }
Dette må heller fikses i selve SVG fil

2021-02-04 08:46 UTC, azaxarov commented on src/components/data-source-item/styled.ts
> +const ServiceIcon = styled(ServiceIconBase)``;
Disse ikonene trenger ikke styled wrapper hvis ikke det er noen stiler

2021-02-04 08:46 UTC, azaxarov commented on package.json
> +    "react-scroll": "^1.8.1",
Er denne i bruk?

2021-02-04 08:53 UTC, jeffreiffers commented on src/components/data-source-item/styled.ts
> +  background-color: #d5edf2;
Snakket med Lene og hu har ikke bekreftet at disse fargene faktisk er riktig. Basert på det så har jeg valgt fargene som står i hennes design og avventer til hu har gått gjennom det som ligger i komponent biblioteket.

2021-02-04 08:54 UTC, jeffreiffers commented on src/entrypoints/main/router/styled.ts
> +      font-size: calc(24px + (48 - 24) * ((100vw - 320px) / (1020 - 320)));
Dette er noe som ligger der fra før. Alexander kan eventuelt forklare nærmere.

2021-02-04 08:58 UTC, jeffreiffers commented on src/components/data-source-item-editor/index.tsx
> +              label='Organization number'
Forsøker å være konsekvent. Apiet bruker US stil og har derfor gjort det likt alle steder.

2021-02-04 08:58 UTC, jeffreiffers commented on src/components/data-source-item-editor/validation-schema.ts
> +    .matches(/^\d{9}$/, 'Organization number must be a 9-digit value'),
Samme som forrige

2021-02-04 09:01 UTC, jeffreiffers commented on package.json
> +    "react-scroll": "^1.8.1",
Nei, glemt å rydde

2021-02-04 09:03 UTC, jeffreiffers commented on src/components/data-source-item/styled.ts
> +  & > button {
Nei sikkert ikke

2021-02-04 09:03 UTC, jeffreiffers commented on src/components/data-sources-page/index.tsx
> +  const getOrganization = (id: string): Organization =>
Enig

2021-02-04 09:31 UTC, oyvindis commented on src/entrypoints/main/router/styled.ts
> +      font-size: calc(24px + (48 - 24) * ((100vw - 320px) / (1020 - 320)));
Ok, men er det poeng å ha fluid-typography? Generelt vil ikke px-units fungere godt med UU-krav da font ikke skalerer like bra med browser-font og zoom.

Er noen eksempler her på hva jeg mener: https://www.24a11y.com/2019/pixels-vs-relative-units-in-css-why-its-still-a-big-deal/

2021-02-04 11:26 UTC, azaxarov commented on src/components/data-source-item/styled.ts
> +  & > button {
Så litt feil på det. Likevel margin right gjør at siste knapp får margin, selv om det er ikke nødvendig. Dermed kunne vi beholdt nth of type og brukt margin-left i stedet

2021-02-04 11:29 UTC, azaxarov reviewed
Se ting som er fortsatt unresolved

2021-02-10 11:11 UTC, azaxarov requested changes

2021-02-10 11:11 UTC, azaxarov commented on src/components/delegation-page/components/side-bar/styled.ts
> +const SideBar = styled('div')`
```suggestion
const SideBar = styled.div`
```

2021-02-10 11:11 UTC, azaxarov commented on src/components/expansion-panel/index.tsx
> +import { Collapse } from 'react-collapse';
Vi trenger ikke dra inn en ny komponent - vi har egen i fdk-portal allerede

2021-02-10 11:11 UTC, azaxarov commented on src/components/expansion-panel/styled.ts
> +const Panel = styled('div')`
```suggestion
const Panel = styled.div`
```

2021-02-10 11:11 UTC, azaxarov commented on src/components/expansion-panel/styled.ts
> +const Header = styled('div')`
```suggestion
const Header = styled.div`
```

2021-02-10 11:11 UTC, azaxarov commented on src/components/expansion-panel/styled.ts
> +  padding-top: 10px;
bruk spacing

2021-02-10 11:11 UTC, azaxarov commented on src/components/expansion-panel/styled.ts
> +  padding: 5px 20px;
bruk spacing

2021-02-10 11:11 UTC, azaxarov commented on src/components/search-field/index.tsx
> +import SC from './styled';
```suggestion

import ClearIcon from '../../images/clear-icon.svg';

import SC from './styled';
```

2021-02-10 11:11 UTC, azaxarov commented on src/components/search-field/index.tsx
> +    onClick('');
hvorfor onClick her?

2021-02-10 11:11 UTC, azaxarov commented on src/components/search-field/styled.ts
> +const TextField = styled('div')`
```suggestion
const TextField = styled.div`
```

2021-02-10 11:11 UTC, azaxarov commented on src/components/search-field/styled.ts
> +const Input = styled('input')`
```suggestion
const Input = styled.input`
```

2021-02-10 11:11 UTC, azaxarov commented on src/components/with-data-sources/index.tsx
> +import { DataSource, SnackbarVariant } from '../../types';
```suggestion

import type { DataSource, SnackbarVariant } from '../../types';
```

2021-02-10 11:11 UTC, azaxarov commented on src/components/with-data-sources/redux/reducer.ts
> +  organizations: [],
```suggestion
```

2021-02-10 11:11 UTC, azaxarov commented on src/components/with-data-sources/redux/reducer.ts
> +        .set('isFetching', false);
Bruk gjerne isLoading som er nærmere konvensjon

2021-02-10 11:11 UTC, azaxarov commented on src/components/with-data-sources/redux/reducer.ts
>    dataSources: [],
Legg inn initiell state for isLoading

2021-02-10 11:11 UTC, azaxarov commented on src/components/with-delegations/index.tsx
> +import { Delegatee } from '../../types';
```suggestion

import type { Delegatee } from '../../types';
```

2021-02-10 11:11 UTC, azaxarov commented on src/components/with-delegations/index.tsx
> +    delegatees: state.DelegationsReducer.get('delegatees')?.toJS() ?? null
Denne skal aldri være null 
```suggestion
    delegatees: state.DelegationsReducer.get('delegatees').toJS()
```

2021-02-10 11:11 UTC, azaxarov commented on src/components/with-filter/index.tsx
> +import React, { ComponentType, memo } from 'react';
Denne komponent bør ikke eksistere på egenhånd. Det finnes en sterk tilknytting til datasources domenemodell

2021-02-10 11:11 UTC, azaxarov commented on src/components/with-organizations/index.tsx
> +import { Organization } from '../../types';
```suggestion

import type { Organization } from '../../types';
```

2021-02-10 11:11 UTC, azaxarov commented on src/components/with-organizations/index.tsx
> +const withDataSources = (Component: ComponentType<any>) => {
```suggestion
const withOrganizations = (Component: ComponentType<any>) => {
```

2021-02-10 11:11 UTC, azaxarov commented on src/components/with-organizations/index.tsx
> +      state.OrganizationsReducer.get('organizations')?.toJS() ?? null
```suggestion
      state.OrganizationsReducer.get('organizations').toJS()
```

2021-02-10 11:11 UTC, azaxarov commented on src/components/with-organizations/redux/reducer.ts
> +import { Actions } from '../../../types';
```suggestion
import type { Actions } from '../../../types';
```

2021-02-10 11:11 UTC, azaxarov commented on src/components/with-organizations/redux/saga.ts
> +import { Organization } from '../../../types';
```suggestion
import type { Organization } from '../../../types';
```

2021-02-10 11:11 UTC, azaxarov commented on src/components/with-organizations/redux/saga.ts
> +          organizationId: ids.join(',')
```suggestion
          organizationId: ids.join()
```

2021-02-10 16:12 UTC, jeffreiffers commented on src/components/data-source-item/index.tsx
> +                {description.length > 0 ? description : '?'}
Når description er tom så ser det veldig rart ut. Subtitle flytter da oppover.

2021-02-11 08:41 UTC, oyvindis commented
Et forslag er å splitte PR til å inneholde færre commits og merge fortløpende så slipper du at en PR blir stående så lenge.

2021-02-11 11:29 UTC, azaxarov approved these changes

2021-02-11 11:29 UTC, azaxarov commented on package.json
> +    "reactstrap": "^8.9.0",
Er denne i bruk?

2021-02-16 08:20 UTC, merged